# Generated by Django 4.2.29 on 2026-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
