# Generated by Django 6.0.3 on 2026-04-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_property_views_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Saralangan', 'verbose_name_plural': 'Saralanganlar'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': "E'lon", 'verbose_name_plural': "E'lonlar"},
        ),
    ]
