# Generated by Django 5.1.15 on 2026-04-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_category_options_alter_favorite_options_and_more'),
        ('base', '0008_property_status'),
    ]

    operations = [
    ]
