# Generated by Django 5.1.15 on 2026-04-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_20260411_0359'),
        ('base', '0009_userprofile_telegram_id'),
    ]

    operations = [
    ]
