# Generated by Django 5.1.15 on 2026-04-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_20260412_0740'),
        ('base', '0010_userprofile_telegram_photo_url'),
    ]

    operations = [
    ]
