from django.urls import path, include
from . import views
from . import panel_views

urlpatterns = [
    path('', views.home, name='home'),
    path('property/<int:pk>/', views.property_detail, name='property_detail'),
    path('seller/<str:username>/', views.seller_profile, name='seller_profile'),
    path('add/', views.add_property, name='add_property'),
    path('property/<int:pk>/edit/', views.edit_property, name='edit_property'),
    path('property/<int:pk>/delete/', views.delete_property, name='delete_property'),
    path('signup/', views.signup, name='signup'),
    path('favorites/', views.favorites, name='favorites'),
    path('favorite/toggle/<int:pk>/', views.toggle_favorite, name='toggle_favorite'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('help/', views.help_page, name='help'),
    path('ai-chat/', views.ai_chat, name='ai_chat'),
    path('ai-whisper/', views.ai_whisper, name='ai_whisper'),
    path('ai-tts/', views.ai_tts, name='ai_tts'),
    path('telegram-auth/', views.telegram_auth, name='telegram_auth'),
    path('set-city/<str:city>/', views.set_city, name='set_city'),
    path('set-language/<str:lang>/', views.set_language, name='set_language'),
    path('accounts/', include('django.contrib.auth.urls')),

    # ── Custom Panel ──────────────────────────────────────────────────────────
    path('panel/',                                        panel_views.panel_home,                    name='panel_home'),
    path('panel/properties/',                             panel_views.panel_properties,              name='panel_properties'),
    path('panel/properties/<int:pk>/edit/',               panel_views.panel_property_edit,           name='panel_property_edit'),
    path('panel/properties/<int:pk>/delete/',             panel_views.panel_property_delete,         name='panel_property_delete'),
    path('panel/properties/<int:pk>/toggle-premium/',     panel_views.panel_property_toggle_premium, name='panel_property_toggle_premium'),
    path('panel/properties/image/<int:pk>/delete/',       panel_views.panel_property_image_delete,   name='panel_property_image_delete'),
    path('panel/users/',                                  panel_views.panel_users,                   name='panel_users'),
    path('panel/users/<int:pk>/',                         panel_views.panel_user_detail,             name='panel_user_detail'),
    path('panel/users/<int:pk>/toggle-block/',            panel_views.panel_user_toggle_block,       name='panel_user_toggle_block'),
    path('panel/users/<int:pk>/toggle-staff/',            panel_views.panel_user_toggle_staff,       name='panel_user_toggle_staff'),
    path('panel/users/<int:pk>/delete/',                  panel_views.panel_user_delete,             name='panel_user_delete'),
    path('panel/categories/',                             panel_views.panel_categories,              name='panel_categories'),
    path('panel/categories/save/',                        panel_views.panel_category_save,           name='panel_category_save'),
    path('panel/categories/<int:pk>/delete/',             panel_views.panel_category_delete,         name='panel_category_delete'),
    path('panel/favorites/',                              panel_views.panel_favorites,               name='panel_favorites'),
    path('panel/stats/',                                  panel_views.panel_stats,                   name='panel_stats'),
    path('panel/search/',                                 panel_views.panel_search,                  name='panel_search'),
    path('panel/search/ajax/',                            panel_views.panel_search_ajax,             name='panel_search_ajax'),
    path('panel/export/properties/',                      panel_views.panel_export_properties,       name='panel_export_properties'),
    path('panel/export/users/',                           panel_views.panel_export_users,            name='panel_export_users'),
]
